import { Modelo } from '../../interfaces/modelo-grafico.interface';

export const animacionConfeti: Modelo[] = [
  {
    nombre: 'confeti_1',
    traslacion: [0, 0, 0],
    escalado: [.5, .5, .5],
    rotacion: [0, 0, 0],
    tipo: 'confeti',
    mostrarAnimacion: false,
    repetirAnimacion: false,
    pintar: true,
    zoom: -10,
    frame: 1,
  },
  {
    nombre: 'confeti_2',
    traslacion: [0, 0, 0],
    escalado: [.5, .5, .5],
    rotacion: [0, 0, 0],
    tipo: 'confeti',
    mostrarAnimacion: true,
    repetirAnimacion: false,
    pintar: false,
    zoom: -10,
    frame: 2,
  },
  {
    nombre: 'confeti_3',
    traslacion: [0, 0, 0],
    escalado: [.5, .5, .5],
    rotacion: [0, 0, 0],
    tipo: 'confeti',
    mostrarAnimacion: true,
    repetirAnimacion: false,
    pintar: false,
    zoom: -10,
    frame: 3,
  },
  {
    nombre: 'confeti_4',
    traslacion: [0, 0, 0],
    escalado: [.5, .5, .5],
    rotacion: [0, 0, 0],
    tipo: 'confeti',
    mostrarAnimacion: true,
    repetirAnimacion: false,
    pintar: false,
    zoom: -10,
    frame: 4,
  },
  {
    nombre: 'confeti_5',
    traslacion: [0, 0, 0],
    escalado: [.5, .5, .5],
    rotacion: [0, 0, 0],
    tipo: 'confeti',
    mostrarAnimacion: true,
    repetirAnimacion: false,
    pintar: false,
    zoom: -10,
    frame: 5,
  },
  {
    nombre: 'confeti_6',
    traslacion: [0, 0, 0],
    escalado: [.5, .5, .5],
    rotacion: [0, 0, 0],
    tipo: 'confeti',
    mostrarAnimacion: true,
    repetirAnimacion: false,
    pintar: false,
    zoom: -10,
    frame: 6,
  },
  {
    nombre: 'confeti_7',
    traslacion: [0, 0, 0],
    escalado: [.5, .5, .5],
    rotacion: [0, 0, 0],
    tipo: 'confeti',
    mostrarAnimacion: true,
    repetirAnimacion: false,
    pintar: false,
    zoom: -10,
    frame: 7,
  },
  {
    nombre: 'confeti_8',
    traslacion: [0, 0, 0],
    escalado: [.5, .5, .5],
    rotacion: [0, 0, 0],
    tipo: 'confeti',
    mostrarAnimacion: true,
    repetirAnimacion: false,
    pintar: false,
    zoom: -10,
    frame: 8,
  },
  {
    nombre: 'confeti_9',
    traslacion: [0, 0, 0],
    escalado: [.5, .5, .5],
    rotacion: [0, 0, 0],
    tipo: 'confeti',
    mostrarAnimacion: true,
    repetirAnimacion: false,
    pintar: false,
    zoom: -10,
    frame: 9,
  },
  {
    nombre: 'confeti_10',
    traslacion: [0, 0, 0],
    escalado: [.5, .5, .5],
    rotacion: [0, 0, 0],
    tipo: 'confeti',
    mostrarAnimacion: true,
    repetirAnimacion: false,
    pintar: false,
    zoom: -10,
    frame: 10,
  }
]
