export { TEntidad } from './TEntidad';
export { TCamara } from './TCamara';
export { TGestorRecursos } from './TGestorRecursos';
export { TLuz } from './TLuz';
export { TMalla } from './TMalla';
export { TNodo } from './TNodo';
export { TRecurso } from './TRecurso';
export { TRecursoMalla } from './TRecursoMalla';
export { TRecursoShader } from './TRecursoShader';
